### ISSUE TITLE
failed to execute script main

### ISSUE THREAD

**Issue by rambo2002** [DotBow/Blender-Version-Manager#30]
Hi,
thx for your greate work. I have a problem starting BVM. This is the error report:
ERROR:__main__:Uncaught exception
Traceback (most recent call last):
  File "main.py", line 56, in <module>
  File "main.py", line 47, in main
  File "main_window.py", line 117, in __init__
  File "main_window.py", line 228, in collect_versions
  File "version_layout.py", line 136, in __init__
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:/Users/*****/AppData/Roaming/Blender Foundation/Blender\\Git-e5ace51295b9-15-May-17-29\\blender.exe', '-v']' returned non-zero exit status 3221225477.

any solutions?

**Comment by DotBow** [comment]
Hi!
This project no longer supported, please visit [Blender Launcher](https://github.com/DotBow/Blender-Launcher) repository for new versions.
As for your issue, it seems you are using a Windows UAC protected directory as Root Folder (AppData folder). It is unsafe and may cause unexpected behavior. Create folder on non system disk for storing builds.
